### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by aharmax** [vadim0x60/cibi#28]
Hi Vadim, 

thanks for the great package!Unfortunately, I got stuck in the installation with the following version issues: 
Successfully built gym gym-sepsis wrapt
ERROR: astroid 2.3.3 requires typed-ast<1.5,>=1.4.0; implementation_name == "cpython" and python_version < "3.8", which is not installed.
ERROR: thinc 6.10.3 has requirement wrapt<1.11.0,>=1.10.0, but you'll have wrapt 1.12.1 which is incompatible.
ERROR: spacy 2.0.12 has requirement regex==2017.4.5, but you'll have regex 2020.2.20 which is incompatible.
ERROR: econml 0.6.1 has requirement matplotlib<3.1, but you'll have matplotlib 3.1.3 which is incompatible.
ERROR: econml 0.6.1 has requirement scikit-learn~=0.21.0, but you'll have scikit-learn 0.22.1 which is incompatible.
ERROR: astroid 2.3.3 has requirement wrapt==1.11.*, but you'll have wrapt 1.12.1 which is incompatible.
Installing collected packages: pyglet, box2d-py, gym, deap, gym-sepsis, wrapt
  Attempting uninstall: wrapt
    Found existing installation: wrapt 1.10.11
ERROR: Cannot uninstall 'wrapt'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

Are these critical to solve or is there another workaround, other than up/down versioning some of the packages?

**Comment by vadim0x60** [comment]
Well, tensorflow 1.15 depends on wrapt 1.11 and tensorflow is definitely important.
I'd suggest either doing `pip install tensorflow==1.13.*` (it doesn't depend on wrapt) or using a virtualenv.

**Comment by vadim0x60** [comment]
Why not create a virtualenv?

If that's not an option, I can suggest `pip install tensorflow==1.13.*` (version 1.13, unlike 1.15, doesn't depend on wrapt).

**Comment by aharmax** [comment]
thanks, I got it installed in virtualenv and ran some tests successfully. A well-built package.

**Comment by vadim0x60** [comment]
Closed for now
Please let me know if you run into any other issues
